services:
  db:
    image: postgres:latest
    container_name: elecctro_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations

  # Adicionar um serviço para executar as migrations
  migration:
    image: node:latest
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install knex pg &&
             npx knex migrate:latest"

volumes:
  pgdata: