export const TODO_STATES = {
    COMPLETE: 'COMPLETE',
    INCOMPLETE: 'INCOMPLETE'
};

export const SORT_FIELDS = {
    DESCRIPTION: 'DESCRIPTION',
    CREATED_AT: 'CREATED_AT',
    COMPLETED_AT: 'COMPLETED_AT'
} ; 